### ISSUE TITLE
Design Doc Review (MVP + Schema) 

### ISSUE THREAD

**Issue by rlim92** [edmondthui/e1finance#1]
Hey Edmond! Design docs looking good so far. Some suggestions below: 

### MVP: 
- [x] Add, `hosting on heroku` and `production readme` as MVPs as well and keep `Account history` as a bonus, after completing the four core MVPs. 

Really solid work here on the MVPs. 

### Schema: 
- [x] for `portfolio` is it possible to not have a `value` column but grab a consolidated value based on the pies inside of it? 
- [x] i noticed `pies` have a `stock_id`. My initial assumption was that pies would `have_many` stocks or maybe holdings of a stock, is it the other way around?

Great work so far!

**Comment by edmondthui** [comment]
- added hosting on heroku
- added production readme
- changed account history to bonus
- removed value from portfolio & pie, will grab value using holdings & stock info
- removed stock_id from pies and added pie_id to holdings (may need to revisit)
