### ISSUE TITLE
Design Doc Review (Sample State + Backend/Frontend Routes) 

### ISSUE THREAD

**Issue by rlim92** [edmondthui/e1finance#2]
Hey Edmond! Design docs looking good so far, some suggestions below: 

### Sample State: 
- [x] are `slices` individual pieces of a pie? Can a user have multiple pies? If so need a reference to what `pie_id`

### Backend Routes:
- [x] how much data will grabbing the portfolios grab? 

### Frontend Routes: 
- [x] Looks good here!

Great work on these.

**Comment by edmondthui** [comment]
- changed slices to pies for clarity
- talked over backend & frontend routes in meeting
- portfolios `has_many` pies and will grab all pies when clicked
- pies `has_many` stocks through holdings and will grab all stocks when clicked
- showed Rich M1Finance features
